### PR TITLE
WIP Impl btn styles

### PR DESCRIPTION
**Pull request by danleyb2**
Have created a new component **components/IdeaBtn.vue** that scopes the new button styles.

We will now have to include `nuxt-link` in places where v-btn was used as a link

### CODE REVIEW

**Comment by danleyb2** [comment]
please review my progress before i update the rest of the buttons to use the new button component

**Comment by aldarund** [comment]
>We will now have to include nuxt-link in places where v-btn was used as a link

that's totally wrong.  Its not valid HTML to have button inside a ( nuxt-link )

**Comment by aldarund** [comment]
Why do we need custom button instead of customizing vuetify vbtn to new styles?

**Comment by danleyb2** [comment]
@aldarund why is it wrong to have a button inside **nuxt-link** 
I created a custom component because the designer provided the css, v-btn applies some of it's styles using `!important` so it be impossible to override all the stylings

**Comment by danleyb2** [comment]
@aldarund is it okay if i use !important to override vuetify , personally i don't think it's the right way

**Comment by danleyb2** [comment]
@aldarund have created a new branch with overriding v-btn 

please check [here](https://github.com/ezl/dailyidea.com/compare/impl_btn_styles_vbtn) and tell if this is what to go with

**Comment by aldarund** [comment]
Its wrong because its not valid html. nuxt link is an a tag. Its not valid to have button tag inside a tag

https://stackoverflow.com/a/6393863/239354

**Comment by aldarund** [comment]
As for that branch, a lot of this values can and should be overridden in vuetify sass variables like sizes, fonts, colors etc
https://vuetifyjs.com/en/components/buttons/ see sass section

**Comment by f-prime** [comment]
> @aldarund why is it wrong to have a button inside **nuxt-link**

~aldarund also mentioned this but to reiterate.

```
<nuxt-link>
  <button>Hello</button>
</nuxt-link>
```

resolves to

```
<a>
   <button>Hello</button>
</a>
```

which is invalid HTML. We ran into a similar problem a while back and it resulted in a bunch of undefined behavior that was causing issues. So it cannot be done this way. 

> is it okay if i use !important to override vuetify , personally i don't think it's the right way

We do this around the app mainly because we have to override vuetify styles in some places. I agree it doesn't feel like the right way, but sometimes it has to be done. Often the Vuetify elements have cleaner ways of overriding certain element styles like ~aldarund has mentioned. Those should be explored first before using `!important`

I still don't think using a component approach is a bad idea, but I think instead it should just wrap `v-btn` and do nothing but modify the style for that specific button component. Not all `v-btn`s are used as links so we need to still have all the functionality of the button component. 

@aldarund knows vuetify better than I do so he seems to have confirmed that the first idea you proposed in slack may be the better bet. The nuxt.config.js file contains the vuetify theme variables. I am not sure how this could be used to create conditional buttons (disabled, clicked, etc) without creating either global styles or button components though.

**Comment by danleyb2** [comment]
Understood the invalid html bit

**Comment by danleyb2** [comment]
new PR https://github.com/ezl/dailyidea.com/pull/510

**Pull request closed without merging**
