### PR TITLE
Fix welcome font sizes

### LINKED ISSUE #600: [landing page] Fix font sizes at all screen widths
https://monosnap.com/file/iGmOiOPFUB5AvalbY1T96y1n9iQ3g6

Especially the 2nd widest setting has badly sized fonts. Between the largest (ok), 2nd largest (fonts are WAY too big), and 3rd (also ok), these aren't scaling well.

If there are default font sizings in whatever framework we are using, we should use that. If not, try to put in global defaults so we don't have to manually define these on every page.

### PR DESCRIPTION
**Pull request by danleyb2**
close #600

### CODE REVIEW

**Comment by vedmant** [comment]
Not sure if it's part of this commit, but the height of the card goes out of screen: https://prnt.sc/v97amf , on mobile as well. Also not sure if this is correct layout https://prnt.sc/v97b2w looks weird, @ezl do we need two columns here at all, it shows only from 960px to 1263px.

**Comment by vedmant** [comment]
@ezl I can test it more and check tomorrow if the issue was present before PR.

**Comment by vedmant** [comment]
The card height is too hight on dev branch too, so it's not introduced in this PR, I'll create an issue for this @ezl

**Comment by vedmant** [comment]
@danleyb2 lgtm but conflicts

**Comment by danleyb2** [comment]
@vedmant conflicts resolved!. 
Have included a single `class` change you did in 5a0bb1321a2c20218271c2afddfb70e1308973cf

**Pull request merged**
