### PR TITLE
WIP Landing page swipe pattern

### LINKED ISSUE #487: implement new swipe pattern landing pages
@alisonuxdesign can you add the screens for the new landing page that start with the swipe pattern immediately for the user?

please make sure to include both mobile and desktop screens please

### PR DESCRIPTION
**Pull request by danleyb2**
fixes #487

### Overview

I moved the swipe functionality  from **pages/i/_shortId/_slug.vue** into a new component **components/IdeaExplorer.vue**
This component is then re-used to implement the new swipe pattern in  **pages/index.vue**

The new swipe cards are implemented in **components/welcome2/** and they are displayed instead of the normal Idea cards by **components/IdeaExplorer.vue** into **components/ideaDetail/Swiper.vue** at start. (when the `ideaIndex` is 0,1,2 and 3 )

### CODE REVIEW

**Comment by danleyb2** [comment]
@f-prime @aldarund The UI and core structure for displaying the cards is ready for review. 
However the flow of the cards and user experience such as _when should some of the Links be displayed or active_ is still pending. i have a few questions on that

**Comment by f-prime** [comment]
@danleyb2 a few things

1. When I signup I still get redirected to /ideas/all which is displaying the old welcome cards
2. There is no need to preserve the original welcome cards and create `welcome2/` just overwrite the original. It's in the git history if we need to revert for whatever reason it's there. No reason to create `welcome2/`
3. Clicking the arrows seems to be broken (I imagine that's what you meant by "flow of the cards" isn't working yet?)
4. https://gyazo.com/e8c717f0dc843c77d72df1ab2596677e
5. The card doesn't seem to rotate when swiping? Is this intentional?

**Comment by ezl** [comment]
@danleyb2 just checking that you saw this has feedback

**Comment by danleyb2** [comment]
@f-prime 
1. How should the flow be here? are the new cards supposed to be displayed on signup too?
2. Have deleted the old welcome cards
3. The arrows work okay on my end. 
4. I am not sure on how to handle the overflow in card. should i hide or allow scrolling
5. The cards do rotate on my end. I re-used the existing swipe implementation
6. Have converted icons directly tied to the UI into components, 
However i am not sure on how to handle the dynamic icons used in the swipe cards

**Comment by f-prime** [comment]
@danleyb2 

1. Should be confirmed with @alisonuxdesign and @ezl but my understanding is that there are a set of cards on sign up as well as the ones you have implemented. After viewing the changes in your PR I am also wondering if #481 is different from this
2. Great, I see that.
3. They also work on my end but I think the issue is with the ideas that get queued which isn't part of this PR
4. The overflow looks like a spacing issue. There shouldn't need to be scroll just maybe change the amount of padding on shorter screens? This also seems to be a big problem on a real mobile device (though it also shows up in the browser). The card is overflowing over the bottom nav. (File) . It seems like the image size is the issue so just scaling that should be fine

5. Yeah, it seems like you are using the swipe component correctly, but the card rotation style is not being applied as expected to the idea-card component so there is no rotation. It may have something to do with the errors in the console. See the gif. 
no-rotate

6. Which dynamic icons? It does seem to be working well on mobile right now though - no flashing of the images at all.

**Comment by danleyb2** [comment]
@f-prime Yes this is similar with #481 as this landing page implementation slides into showing ideas after the initial cards

**Comment by danleyb2** [comment]
@ezl I am not if the **Ideas** are to also be covered with this because a card showing an idea details is included here.
@f-prime Can you please point me to where i can test and see the swipe rotation? 
Also how should we handle conflict from you already working on #481 and i already implementing some features

**Comment by ezl** [comment]
1. regarding flow, @f-prime is correct. the cards in #487 are basically the "landing page". the card in #481 is displayed the first time after sign up. they are independent, even though the "post signup" card conveys similar information.

2-6. you guys seem to be discussing this fine and don't need input from me so I will skip.

**Comment by danleyb2** [comment]
@f-prime 
- This now contains only the Landing page cards without dropping the user into the ideas queue.
- Have also implemented the sub nav but will include it after https://github.com/ezl/dailyidea.com/pull/537 is merged as it requires adding a slot in the Layout
- Displaying the Ideas queue after the cards will be handled by #481 to prevent conflicts from difference in implementation and other pending PRs that modify idea details components

**Comment by f-prime** [comment]
@danleyb2 This is fine but since #481 isn't even in progress yet the explainer cards can't just go nowhere after. Right now at the end of the explainer cards all that is shown are blank cards which isn't correct. I think leaving the queue in would have been fine. If that isn't possible for whatever reason then maybe redirecting to the ideas page or something would be fine until #481 or some similar issue fixes this. It can't just go nowhere though so this needs to be fixed before I can merge it.

Also, the overflow issue is still there but if that is too difficult to fix for whatever reason we will push it. There are some card height issues that need to be addressed elsewhere anyway.

**Comment by f-prime** [comment]
This worked perfectly, merging

**Pull request merged**
