### PR TITLE
Issue 495 - My Ideas

### PR DESCRIPTION
**Pull request by f-prime**
This PR implements #495

Here is what's left out:

- Settings page (Moved to #528 )
- Mobile edit page full screen input (Moved to #528 )
- Post settings (Moved to #536 )

(Desktop)

(Mobile)

### CODE REVIEW

**Review by vedmant — CHANGES_REQUESTED** [review]
1. I see that my ideas page looks off, not as in the design: 
Screenshot at Sep 10 10-37-40

2. Spotted bug, when clicking on site logo from other pages, it shows 404 page.

3. Card when user has no ideas is also off to the right, the same with saved ideas.
Screenshot at Sep 10 10-48-32

We might need to use some common card components, as we use cards not only for ideas, currently it's IdeaCard but used not only for ideas.

Otherwise code looks ok for me.

**Comment by f-prime** [comment]
Thanks for catching this @vedmant I fixed it by removing the specific bits of CSS in the IdeaCard component that were doing this and let the page using IdeaCard or FullIdea to pass styling as a prop... 

I agree we need to create a more general card component that can be manipulated from directly inside other components (setting width and height properly, etc). IdeaCard is _supposed to_ be that that, but as we can see it's still not general enough.

**Review by aldarund — APPROVED** [review]

**Comment by vedmant** [comment]
@f-prime After edits background skeleton size card is not matching cards, could you adjust it

Screenshot at Sep 11 18-54-27

**Comment by f-prime** [comment]
@vedmant The fixes have been pushed. Thanks!

**Review by vedmant — APPROVED** [review]

**Pull request merged**
